studyswift:
	git clone git://github.com/mozilla/pdf.js.git
	sudo npm install -g gulp-cli
	sudo npm install --prefix ./pdf.js
	cp studySwift.js ./pdf.js/web/
	cp summary.js ./pdf.js/web/
	cp summary.html ./pdf.js/web/
	cp summary.css ./pdf.js/web/
	cp viewer.html ./pdf.js/web/

noClone:
	sudo npm install -g gulp-cli
	sudo npm install --prefix ./pdf.js
	cp studySwift.js ./pdf.js/web/
	cp summary.js ./pdf.js/web/
	cp summary.html ./pdf.js/web/
	cp summary.css ./pdf.js/web/
	cp viewer.html ./pdf.js/web/


update:
	cp studySwift.js ./pdf.js/web/
	cp summary.js ./pdf.js/web/
	cp summary.html ./pdf.js/web/
	cp summary.css ./pdf.js/web/
	cp viewer.html ./pdf.js/web/
